"""empty message

Revision ID: cf6609a0181a
Revises: 442ce066547e
Create Date: 2022-08-11 17:54:14.324903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6609a0181a'
down_revision = '442ce066547e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'talent_looking')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('talent_looking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
